import {
  BarChart3,
  Bot,
  CalendarDays,
  ClipboardList,
  Clock,
  CreditCard,
  FileSignature,
  FileText,
  Globe,
  Map,
  MessageSquareText,
  Phone,
  Receipt,
  Rocket,
  Ruler,
  Settings,
  Smartphone,
  Target,
  Users,
  UsersRound,
  Wallet,
  Workflow,
  type LucideIcon,
} from "lucide-react";
import type { HelpIconKey } from "@/lib/help/types";

export const HELP_ICONS: Record<HelpIconKey, LucideIcon> = {
  start: Rocket,
  clients: Users,
  leads: Target,
  jobs: ClipboardList,
  schedule: CalendarDays,
  quotes: FileText,
  agreements: FileSignature,
  invoices: Receipt,
  payments: CreditCard,
  estimator: Ruler,
  phone: Phone,
  texting: MessageSquareText,
  automations: Workflow,
  atlas: Bot,
  team: UsersRound,
  time: Clock,
  routes: Map,
  portal: Globe,
  reports: BarChart3,
  settings: Settings,
  mobile: Smartphone,
  billing: Wallet,
};
