/**
 * Shared calendar vocabulary — the DTO the server hands the schedule page,
 * the date helpers every renderer uses, and the lifecycle tones. Pulled out
 * of ScheduleClient so the month grid, time grid, palette, and sheets can be
 * separate files that agree on one set of types.
 */

// Blocked-off time riding along in the DTO — the calendar shows per-day
// segments but the sheet edits the underlying block's full range.
export type BlockInfo = {
  id: string;
  userId: string | null; // null = everyone (company-wide)
  userName: string | null;
  title: string;
  startAt: string;
  endAt: string;
  allDay: boolean;
  /** Optional "where I'll be" — routing treats a located block as a stop. */
  address: string | null;
  canEdit: boolean;
  /** GOOGLE = mirrored from the user's Google Calendar; read-only here. */
  source: "MANUAL" | "GOOGLE";
};

export type ScheduleJobDTO = {
  id: string;
  kind: "job" | "appointment" | "block";
  jobNumber: number | null;
  title: string;
  status: string;
  apptType: string | null; // PHONE_CALL | VIDEO_CALL | IN_PERSON
  scheduledAt: string | null;
  scheduledEnd: string | null;
  scheduledAnytime: boolean;
  contactName: string;
  contactId?: string | null;
  tentative?: boolean; // self-scheduled booking awaiting approval → dashed
  requestId?: string | null; // tentative bookings accept through their request
  recurring?: boolean; // visit generated by a subscription's visit series
  // Auto-generated visit landed on existing work (Job.conflictNote) — badge
  // until someone reschedules it
  conflictNote?: string | null;
  assignees?: string[]; // who's on it — initials chips on the phone agenda
  assigneeIds?: string[]; // prefills the drop-to-schedule sheet's crew picker
  outsourced?: boolean; // a subcontractor is doing it — empty crew on purpose
  // Scheduled, nobody on it, not outsourced, and the company has more than
  // one member (a one-person company's jobs are auto-assigned) → badge it
  needsCrew?: boolean;
  // Phone agenda swipe actions (call / directions); absent on blocks
  phone?: string | null;
  address?: string | null;
  block?: BlockInfo;
};

/** A client, lead, request, or unscheduled job the palette can drag in. */
export type PaletteEntity =
  | {
      type: "contact";
      id: string;
      name: string;
      lead: boolean; // on the Leads board → defaults to an appointment
      address: string | null;
      phone: string | null;
      sub: string;
    }
  | {
      type: "request";
      id: string;
      title: string;
      contactId: string;
      name: string;
      address: string | null;
      phone: string | null;
      preferredDate: string | null; // YYYY-MM-DD
      sub: string;
    }
  | { type: "job"; job: ScheduleJobDTO }
  | { type: "new"; name: string } // typed a name nobody has → create a client
  | { type: "pick"; kind: "job" | "appointment" }; // painted a range first, pick who after

export type View = "month" | "week" | "day";

/** One-week business hours, minutes since midnight per weekday (0 = Sun). */
export type OpenRange = { start: number; end: number };
export type WeekHours = OpenRange[][]; // index = getDay()

export const HOUR_PX = 48;
export const DAY_NAMES = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
export const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

export const pad = (n: number) => String(n).padStart(2, "0");
export const toParam = (d: Date) => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;

export function parseParam(s: string): Date {
  const [y, m, d] = s.split("-").map(Number);
  return new Date(y, m - 1, d);
}

export function addDays(d: Date, n: number): Date {
  const x = new Date(d);
  x.setDate(x.getDate() + n);
  return x;
}

export function sameDay(a: Date, b: Date): boolean {
  return (
    a.getFullYear() === b.getFullYear() &&
    a.getMonth() === b.getMonth() &&
    a.getDate() === b.getDate()
  );
}

export function startOfWeek(d: Date): Date {
  const x = new Date(d);
  x.setDate(x.getDate() - x.getDay());
  x.setHours(0, 0, 0, 0);
  return x;
}

export function fmtTime(d: Date): string {
  return d.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" }).toLowerCase().replace(" ", "");
}

/** Minutes since midnight → "9:45am" (used by the drag ghost's live badge). */
export function fmtMinute(min: number): string {
  const d = new Date(2000, 0, 1, 0, 0, 0, 0);
  d.setMinutes(Math.max(0, Math.min(24 * 60 - 1, min)));
  return fmtTime(d);
}

export function hourLabel(h: number): string {
  if (h === 0) return "12 AM";
  if (h < 12) return `${h} AM`;
  if (h === 12) return "12 PM";
  return `${h - 12} PM`;
}

export function minutesOf(d: Date): number {
  return d.getHours() * 60 + d.getMinutes();
}

export function atMinute(day: Date, minute: number): Date {
  const x = new Date(day);
  x.setHours(0, 0, 0, 0);
  x.setMinutes(minute);
  return x;
}

export function snapTo(minute: number, step: number): number {
  return Math.round(minute / step) * step;
}

export function durationLabel(minutes: number): string {
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  if (h === 0) return `${m}m`;
  if (m === 0) return `${h}h`;
  return `${h}h ${m}m`;
}

/** Item length in minutes (default hour; blocks and anytime rows report 0). */
export function itemDuration(it: ScheduleJobDTO): number {
  if (!it.scheduledAt || it.scheduledAnytime) return 60;
  if (!it.scheduledEnd) return 60;
  const ms = new Date(it.scheduledEnd).getTime() - new Date(it.scheduledAt).getTime();
  return Math.max(15, Math.round(ms / 60000));
}

/** Anytime first, then in clock order — the one sort every list shares. */
export function sortItems(items: ScheduleJobDTO[]): ScheduleJobDTO[] {
  return [...items].sort((a, b) => {
    if (a.scheduledAnytime !== b.scheduledAnytime) return a.scheduledAnytime ? -1 : 1;
    const dt = new Date(a.scheduledAt!).getTime() - new Date(b.scheduledAt!).getTime();
    if (dt !== 0) return dt;
    // Same start: blocks behind work, then shorter first
    if ((a.kind === "block") !== (b.kind === "block")) return a.kind === "block" ? 1 : -1;
    return itemDuration(a) - itemDuration(b);
  });
}

// Tinted blocks reusing the lifecycle tones (green=active, amber=needs
// invoicing, gray=archived); appointments are the blue family so sales
// meetings scan differently from work.
const blockTone: Record<string, string> = {
  ACTIVE: "border-green-500 bg-green-100 text-green-900 hover:bg-green-200",
  REQUIRES_INVOICING: "border-amber-500 bg-amber-100 text-amber-900 hover:bg-amber-200",
  ARCHIVED: "border-gray-400 bg-gray-100 text-gray-600 hover:bg-gray-200",
};

export function itemTone(it: { kind: string; status: string; tentative?: boolean }): string {
  // Blocked-off time: hatched gray so it reads as "unavailable", not work
  if (it.kind === "block") return "border-gray-400 bg-blocked text-gray-600 hover:bg-gray-200/70";
  if (it.kind === "appointment") {
    if (it.status === "NO_SHOW") return "border-red-400 bg-red-50 text-red-800 hover:bg-red-100";
    if (it.status === "COMPLETED") return "border-blue-300 bg-blue-50 text-blue-700 hover:bg-blue-100";
    // Self-scheduled bookings awaiting approval render hollow/dashed — the
    // slot is held but not confirmed until Accept and Schedule
    if (it.tentative) return "border-dashed border-blue-500 bg-blue-50/60 text-blue-800 hover:bg-blue-100";
    return "border-blue-500 bg-blue-100 text-blue-900 hover:bg-blue-200";
  }
  return blockTone[it.status] ?? blockTone.ARCHIVED;
}

export type TimedLayout = {
  j: ScheduleJobDTO;
  startMin: number;
  endMin: number;
  col: number;
  cols: number;
};

/** Greedy column layout so overlapping blocks share the day column. */
export function layoutTimed(jobs: ScheduleJobDTO[], day: Date): TimedLayout[] {
  const dayStart = new Date(day);
  dayStart.setHours(0, 0, 0, 0);
  const events = jobs
    .map((j) => {
      const s = new Date(j.scheduledAt!);
      const startMin = Math.max(0, (s.getTime() - dayStart.getTime()) / 60000);
      const rawEnd = j.scheduledEnd
        ? (new Date(j.scheduledEnd).getTime() - dayStart.getTime()) / 60000
        : startMin + 60;
      const endMin = Math.min(24 * 60, Math.max(startMin + 30, rawEnd));
      return { j, startMin, endMin, col: 0, cols: 1 };
    })
    .sort((a, b) => a.startMin - b.startMin || a.endMin - b.endMin);

  // Cluster transitively-overlapping events, then assign columns greedily
  let cluster: typeof events = [];
  let clusterEnd = -1;
  const flush = () => {
    const colEnds: number[] = [];
    for (const ev of cluster) {
      let col = colEnds.findIndex((end) => end <= ev.startMin);
      if (col === -1) {
        col = colEnds.length;
        colEnds.push(0);
      }
      colEnds[col] = ev.endMin;
      ev.col = col;
    }
    for (const ev of cluster) ev.cols = colEnds.length;
    cluster = [];
  };
  for (const ev of events) {
    if (cluster.length && ev.startMin >= clusterEnd) flush();
    cluster.push(ev);
    clusterEnd = Math.max(clusterEnd, ev.endMin);
  }
  flush();
  return events;
}

/** "Marcus Reyes" → "MR" for assignee chips. */
export function initialsOf(name: string): string {
  return name
    .split(/\s+/)
    .filter(Boolean)
    .map((w) => w[0]!)
    .slice(0, 2)
    .join("")
    .toUpperCase();
}

/** Human label for a landing spot: "Tue, Sep 15 · 9:45am – 11:15am". */
export function placeLabel(day: Date, minute: number | null, durationMin: number): string {
  const d = day.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" });
  if (minute === null) return `${d} · Anytime`;
  return `${d} · ${fmtMinute(minute)} – ${fmtMinute(minute + durationMin)}`;
}

export function isTouchDevice(): boolean {
  if (typeof window === "undefined") return false;
  return window.matchMedia("(pointer: coarse)").matches;
}

export function isPhoneWidth(): boolean {
  if (typeof window === "undefined") return false;
  return window.matchMedia("(max-width: 1023px)").matches;
}
