"use client";

import { useEffect, useMemo, useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import {
  CalendarClock,
  CalendarDays,
  CalendarOff,
  ChevronLeft,
  ChevronRight,
  GripVertical,
  Loader2,
  MapPin as MapPinIcon,
  Phone as PhoneIcon,
  Plus,
  Repeat as RepeatIcon,
  Trash2,
  Video as VideoIcon,
  X,
} from "lucide-react";
import PageTitle from "@/components/PageTitle";
import { SECTION_HUES } from "@/lib/section-colors";
import { FilterChip, SegmentedRow, Segment } from "@/components/FilterChips";
import { postJson, GENERIC_ERROR } from "@/lib/safe-fetch";

/**
 * Month / Week / Day calendar with an "Anytime" all-day row, an
 * unscheduled-jobs drawer, and drag-to-(re)schedule. Mirrors Jobber's
 * schedule layout (build spec §6) without the map/route extras.
 *
 * Drag rules:
 *  - drop on an hour cell  → starts at that hour, keeps the job's previous
 *    duration (default 1h), clears "anytime"
 *  - drop on the Anytime row / a month day cell with no previous time
 *    → date-only ("anytime", anchored at noon like other date-only fields)
 *  - drop on a month day cell when the job had a time → keeps that time
 */

// Blocked-off time riding along in the DTO — the calendar shows per-day
// segments but the sheet edits the underlying block's full range.
export type BlockInfo = {
  id: string;
  userId: string | null; // null = everyone (company-wide)
  userName: string | null;
  title: string;
  startAt: string;
  endAt: string;
  allDay: boolean;
  canEdit: boolean;
};

export type ScheduleJobDTO = {
  id: string;
  kind: "job" | "appointment" | "block";
  jobNumber: number | null;
  title: string;
  status: string;
  apptType: string | null; // PHONE_CALL | VIDEO_CALL | IN_PERSON
  scheduledAt: string | null;
  scheduledEnd: string | null;
  scheduledAnytime: boolean;
  contactName: string;
  tentative?: boolean; // self-scheduled booking awaiting approval → dashed
  recurring?: boolean; // visit generated by a subscription's visit series
  assignees?: string[]; // who's on it — initials chips on the phone agenda
  block?: BlockInfo;
};

type View = "month" | "week" | "day";

const HOUR_PX = 48;
const DAY_NAMES = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

// Tinted blocks reusing the lifecycle tones (green=active, amber=needs
// invoicing, gray=archived); appointments are the blue family so sales
// meetings scan differently from work.
const blockTone: Record<string, string> = {
  ACTIVE: "border-green-500 bg-green-100 text-green-900 hover:bg-green-200",
  REQUIRES_INVOICING: "border-amber-500 bg-amber-100 text-amber-900 hover:bg-amber-200",
  ARCHIVED: "border-gray-400 bg-gray-100 text-gray-600 hover:bg-gray-200",
};

function itemTone(it: { kind: string; status: string; tentative?: boolean }): string {
  // Blocked-off time: hatched gray so it reads as "unavailable", not work
  if (it.kind === "block") return "border-gray-400 bg-blocked text-gray-600 hover:bg-gray-200/70";
  if (it.kind === "appointment") {
    if (it.status === "NO_SHOW") return "border-red-400 bg-red-50 text-red-800 hover:bg-red-100";
    if (it.status === "COMPLETED") return "border-blue-300 bg-blue-50 text-blue-700 hover:bg-blue-100";
    // Self-scheduled bookings awaiting approval render hollow/dashed — the
    // slot is held but not confirmed until Accept and Schedule
    if (it.tentative) return "border-dashed border-blue-500 bg-blue-50/60 text-blue-800 hover:bg-blue-100";
    return "border-blue-500 bg-blue-100 text-blue-900 hover:bg-blue-200";
  }
  return blockTone[it.status] ?? blockTone.ARCHIVED;
}

function TypeGlyph({
  apptType,
  recurring,
  size = 10,
}: {
  apptType: string | null;
  recurring?: boolean;
  size?: number;
}) {
  if (apptType === "PHONE_CALL") return <PhoneIcon size={size} className="inline shrink-0" />;
  if (apptType === "VIDEO_CALL") return <VideoIcon size={size} className="inline shrink-0" />;
  if (apptType === "IN_PERSON") return <MapPinIcon size={size} className="inline shrink-0" />;
  // Visit from a recurring series (subscription)
  if (recurring) return <RepeatIcon size={size} className="inline shrink-0 opacity-70" />;
  return null;
}

const pad = (n: number) => String(n).padStart(2, "0");
const toParam = (d: Date) => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;

function parseParam(s: string): Date {
  const [y, m, d] = s.split("-").map(Number);
  return new Date(y, m - 1, d);
}

function addDays(d: Date, n: number): Date {
  const x = new Date(d);
  x.setDate(x.getDate() + n);
  return x;
}

function sameDay(a: Date, b: Date): boolean {
  return (
    a.getFullYear() === b.getFullYear() &&
    a.getMonth() === b.getMonth() &&
    a.getDate() === b.getDate()
  );
}

function fmtTime(d: Date): string {
  return d.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" }).toLowerCase().replace(" ", "");
}

function hourLabel(h: number): string {
  if (h === 0) return "12 AM";
  if (h < 12) return `${h} AM`;
  if (h === 12) return "12 PM";
  return `${h - 12} PM`;
}

/** Greedy column layout so overlapping blocks share the day column. */
function layoutTimed(jobs: ScheduleJobDTO[], day: Date) {
  const dayStart = new Date(day);
  dayStart.setHours(0, 0, 0, 0);
  const events = jobs
    .map((j) => {
      const s = new Date(j.scheduledAt!);
      const startMin = Math.max(0, (s.getTime() - dayStart.getTime()) / 60000);
      const rawEnd = j.scheduledEnd
        ? (new Date(j.scheduledEnd).getTime() - dayStart.getTime()) / 60000
        : startMin + 60;
      const endMin = Math.min(24 * 60, Math.max(startMin + 30, rawEnd));
      return { j, startMin, endMin, col: 0, cols: 1 };
    })
    .sort((a, b) => a.startMin - b.startMin || a.endMin - b.endMin);

  // Cluster transitively-overlapping events, then assign columns greedily
  let cluster: typeof events = [];
  let clusterEnd = -1;
  const flush = () => {
    const colEnds: number[] = [];
    for (const ev of cluster) {
      let col = colEnds.findIndex((end) => end <= ev.startMin);
      if (col === -1) {
        col = colEnds.length;
        colEnds.push(0);
      }
      colEnds[col] = ev.endMin;
      ev.col = col;
    }
    for (const ev of cluster) ev.cols = colEnds.length;
    cluster = [];
  };
  for (const ev of events) {
    if (cluster.length && ev.startMin >= clusterEnd) flush();
    cluster.push(ev);
    clusterEnd = Math.max(clusterEnd, ev.endMin);
  }
  flush();
  return events;
}

type BlockForm = {
  title: string;
  who: string; // user id | "everyone" (managers only)
  allDay: boolean;
  startDate: string;
  endDate: string;
  startTime: string;
  endTime: string;
};

export default function ScheduleClient({
  view,
  explicitView = true,
  date,
  team,
  jobs,
  unscheduled,
  users,
  canCreateJob = true,
  canCreateAppointment = true,
  canBlockForOthers = false,
  meId = "",
}: {
  view: View;
  explicitView?: boolean;
  date: string;
  team: string;
  jobs: ScheduleJobDTO[];
  unscheduled: ScheduleJobDTO[];
  users: { id: string; name: string }[];
  canCreateJob?: boolean;
  canCreateAppointment?: boolean;
  canBlockForOthers?: boolean;
  meId?: string;
}) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [dragId, setDragId] = useState<string | null>(null);
  const [hoverKey, setHoverKey] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [mounted, setMounted] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  // Block-off-time sheet: null = closed; id null = creating a new block
  const [blockSheet, setBlockSheet] = useState<null | {
    id: string | null;
    canEdit: boolean;
    userName: string | null; // read-only display when it isn't yours
    form: BlockForm;
  }>(null);
  const [blockBusy, setBlockBusy] = useState(false);
  const [blockErr, setBlockErr] = useState("");

  const anchor = useMemo(() => parseParam(date), [date]);
  const today = useMemo(() => new Date(), []);

  useEffect(() => setMounted(true), []);

  // Open week/day scrolled to the current time when "now" is on screen (an
  // hour of context above it), otherwise to business hours instead of midnight.
  useEffect(() => {
    if (!scrollRef.current) return;
    const now = new Date();
    const nowVisible =
      view === "day"
        ? sameDay(anchor, now)
        : (() => {
            const ws = new Date(anchor);
            ws.setDate(ws.getDate() - ws.getDay());
            ws.setHours(0, 0, 0, 0);
            return now >= ws && now < addDays(ws, 7);
          })();
    scrollRef.current.scrollTop = nowVisible
      ? Math.max(0, ((now.getHours() * 60 + now.getMinutes()) / 60 - 1) * HOUR_PX)
      : 7 * HOUR_PX;
  }, [view, date, anchor]);

  function go(next: { view?: View; date?: Date; team?: string }, replace = false) {
    const v = next.view ?? view;
    const params = new URLSearchParams();
    params.set("view", v);
    params.set("date", toParam(next.date ?? anchor));
    const t = next.team !== undefined ? next.team : team;
    if (t) params.set("team", t);
    const url = `/app/schedule?${params.toString()}`;
    startTransition(() => (replace ? router.replace(url) : router.push(url)));
  }

  // Phones open on today's Day agenda — the month grid is a desktop tool and
  // its truncated chips are unreadable at phone widths. Only when the URL
  // didn't ask for a view explicitly, so shared links still win.
  useEffect(() => {
    if (!explicitView && view !== "day" && window.matchMedia("(max-width: 1023px)").matches) {
      go({ view: "day", date: new Date() }, true);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function step(dir: 1 | -1) {
    if (view === "month") {
      go({ date: new Date(anchor.getFullYear(), anchor.getMonth() + dir, 1) });
    } else {
      go({ date: addDays(anchor, dir * (view === "week" ? 7 : 1)) });
    }
  }

  const allJobs = useMemo(() => {
    const map = new Map<string, ScheduleJobDTO>();
    for (const j of [...jobs, ...unscheduled]) map.set(j.id, j);
    return map;
  }, [jobs, unscheduled]);

  async function scheduleDrop(jobId: string, day: Date, hour: number | "anytime") {
    const job = allJobs.get(jobId);
    if (!job) return;
    setHoverKey(null);
    setDragId(null);

    let startD: Date;
    let endD: Date | null = null;
    let anytime: boolean;

    if (hour === "anytime") {
      startD = new Date(day);
      startD.setHours(12, 0, 0, 0); // date-only convention: anchor at noon
      anytime = true;
    } else if (hour === -1) {
      // month-cell drop: keep the previous time of day if the job had one
      if (job.scheduledAt && !job.scheduledAnytime) {
        const prev = new Date(job.scheduledAt);
        startD = new Date(day);
        startD.setHours(prev.getHours(), prev.getMinutes(), 0, 0);
        anytime = false;
      } else {
        startD = new Date(day);
        startD.setHours(12, 0, 0, 0);
        anytime = true;
      }
    } else {
      startD = new Date(day);
      startD.setHours(hour, 0, 0, 0);
      anytime = false;
    }

    if (!anytime) {
      const prevDur =
        job.scheduledAt && job.scheduledEnd && !job.scheduledAnytime
          ? new Date(job.scheduledEnd).getTime() - new Date(job.scheduledAt).getTime()
          : 60 * 60000;
      endD = new Date(startD.getTime() + Math.max(30 * 60000, prevDur));
    }

    setSaving(true);
    setError("");
    const endpoint =
      job.kind === "appointment" ? `/api/app/appointments/${jobId}` : `/api/app/jobs/${jobId}`;
    const { ok, data } = await postJson(
      endpoint,
      {
        scheduledAt: startD.toISOString(),
        scheduledEnd: endD ? endD.toISOString() : null,
        scheduledAnytime: anytime,
      },
      "PATCH"
    );
    setSaving(false);
    if (!ok) {
      setError(data?.error ?? GENERIC_ERROR);
      return;
    }
    startTransition(() => router.refresh());
  }

  function dragProps(job: ScheduleJobDTO) {
    // Blocked-off time is edited through its sheet, not dragged around
    if (job.kind === "block") return {};
    return {
      draggable: true,
      onDragStart: (e: React.DragEvent) => {
        e.dataTransfer.setData("text/plain", job.id);
        e.dataTransfer.effectAllowed = "move";
        setDragId(job.id);
      },
      onDragEnd: () => {
        setDragId(null);
        setHoverKey(null);
      },
    };
  }

  function dropProps(key: string, day: Date, hour: number | "anytime") {
    return {
      onDragOver: (e: React.DragEvent) => {
        e.preventDefault();
        e.dataTransfer.dropEffect = "move";
        if (hoverKey !== key) setHoverKey(key);
      },
      onDragLeave: () => {
        if (hoverKey === key) setHoverKey(null);
      },
      onDrop: (e: React.DragEvent) => {
        e.preventDefault();
        const id = dragId ?? e.dataTransfer.getData("text/plain");
        if (id) scheduleDrop(id, day, hour);
      },
    };
  }

  const openItem = (it: ScheduleJobDTO) => {
    if (it.kind === "block") {
      if (it.block) openBlockEdit(it.block);
      return;
    }
    router.push(it.kind === "appointment" ? `/app/appointments/${it.id}` : `/app/jobs/${it.id}`);
  };

  // ── Blocked-off time ──────────────────────────────────────────────────────

  function openBlockCreate() {
    const d = toParam(view === "month" ? new Date() : anchor);
    setBlockErr("");
    setBlockSheet({
      id: null,
      canEdit: true,
      userName: null,
      form: {
        title: "",
        who: meId,
        allDay: false,
        startDate: d,
        endDate: d,
        startTime: "09:00",
        endTime: "17:00",
      },
    });
  }

  function openBlockEdit(b: BlockInfo) {
    const s = new Date(b.startAt);
    const e = new Date(b.endAt);
    setBlockErr("");
    setBlockSheet({
      id: b.id,
      canEdit: b.canEdit,
      userName: b.userName,
      form: {
        title: b.title === "Blocked off" ? "" : b.title,
        who: b.userId ?? "everyone",
        allDay: b.allDay,
        startDate: toParam(s),
        endDate: toParam(e),
        startTime: `${pad(s.getHours())}:${pad(s.getMinutes())}`,
        endTime: `${pad(e.getHours())}:${pad(e.getMinutes())}`,
      },
    });
  }

  async function saveBlock() {
    if (!blockSheet) return;
    const f = blockSheet.form;
    if (!f.startDate) {
      setBlockErr("Pick a date.");
      return;
    }
    let startAt: Date;
    let endAt: Date;
    if (f.allDay) {
      startAt = parseParam(f.startDate);
      endAt = parseParam(f.endDate || f.startDate);
      endAt.setHours(23, 59, 59, 999);
    } else {
      const [sh, sm] = f.startTime.split(":").map(Number);
      const [eh, em] = f.endTime.split(":").map(Number);
      startAt = parseParam(f.startDate);
      startAt.setHours(sh || 0, sm || 0, 0, 0);
      endAt = parseParam(f.startDate);
      endAt.setHours(eh || 0, em || 0, 0, 0);
    }
    if (endAt <= startAt) {
      setBlockErr(f.allDay ? "The end date can't be before the start date." : "The end time must be after the start time.");
      return;
    }

    const body: Record<string, unknown> = {
      title: f.title,
      allDay: f.allDay,
      startAt: startAt.toISOString(),
      endAt: endAt.toISOString(),
    };
    if (canBlockForOthers) body.forUserId = f.who === "everyone" ? null : f.who;

    setBlockBusy(true);
    setBlockErr("");
    const { ok, data } = blockSheet.id
      ? await postJson(`/api/app/time-blocks/${blockSheet.id}`, body, "PATCH")
      : await postJson("/api/app/time-blocks", body);
    setBlockBusy(false);
    if (!ok) {
      setBlockErr(data?.error ?? GENERIC_ERROR);
      return;
    }
    setBlockSheet(null);
    startTransition(() => router.refresh());
  }

  async function deleteBlock() {
    if (!blockSheet?.id) return;
    setBlockBusy(true);
    setBlockErr("");
    const { ok, data } = await postJson(`/api/app/time-blocks/${blockSheet.id}`, undefined, "DELETE");
    setBlockBusy(false);
    if (!ok) {
      setBlockErr(data?.error ?? GENERIC_ERROR);
      return;
    }
    setBlockSheet(null);
    startTransition(() => router.refresh());
  }

  // ── Header label ──────────────────────────────────────────────────────────
  // Two lengths: the full range for the desktop bar, and a short one for the
  // phone header, where "Wednesday, July 29, 2026" ran off both edges.
  let rangeLabel: string;
  let shortLabel: string;
  if (view === "month") {
    rangeLabel = `${MONTHS[anchor.getMonth()]} ${anchor.getFullYear()}`;
    shortLabel =
      anchor.getFullYear() === today.getFullYear()
        ? MONTHS[anchor.getMonth()]
        : `${MONTHS[anchor.getMonth()].slice(0, 3)} ${anchor.getFullYear()}`;
  } else if (view === "week") {
    const ws = addDays(anchor, -anchor.getDay());
    const we = addDays(ws, 6);
    const fmt = (d: Date) => d.toLocaleDateString("en-US", { month: "short", day: "numeric" });
    rangeLabel = `${fmt(ws)} – ${fmt(we)}, ${we.getFullYear()}`;
    shortLabel = `${fmt(ws)} – ${fmt(we)}`;
  } else {
    rangeLabel = anchor.toLocaleDateString("en-US", {
      weekday: "long",
      month: "long",
      day: "numeric",
      year: "numeric",
    });
    shortLabel = sameDay(anchor, today)
      ? "Today"
      : anchor.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" });
  }

  const weekDays =
    view === "week"
      ? Array.from({ length: 7 }, (_, i) => addDays(addDays(anchor, -anchor.getDay()), i))
      : [anchor];

  // ── Renderers ─────────────────────────────────────────────────────────────

  function renderMonth() {
    const y = anchor.getFullYear();
    const m = anchor.getMonth();
    const firstDow = new Date(y, m, 1).getDay();
    const daysInMonth = new Date(y, m + 1, 0).getDate();

    const jobsByDay: Record<number, ScheduleJobDTO[]> = {};
    for (const job of jobs) {
      if (!job.scheduledAt) continue;
      const d = new Date(job.scheduledAt);
      if (d.getMonth() !== m || d.getFullYear() !== y) continue;
      (jobsByDay[d.getDate()] ??= []).push(job);
    }

    const cells: React.ReactNode[] = [];
    for (let i = 0; i < firstDow; i++) {
      cells.push(<div key={`e-${i}`} className="min-h-[80px] border-b border-r border-gray-100 bg-gray-50 p-1 lg:min-h-[104px]" />);
    }
    for (let d = 1; d <= daysInMonth; d++) {
      const cellDate = new Date(y, m, d);
      const isToday = sameDay(cellDate, today);
      const dayJobs = jobsByDay[d] ?? [];
      const key = `m-${d}`;
      cells.push(
        <div
          key={d}
          {...dropProps(key, cellDate, -1)}
          className={`min-h-[80px] border-b border-r border-gray-100 p-1.5 transition-colors lg:min-h-[104px] ${
            hoverKey === key ? "bg-green-100/70 ring-2 ring-inset ring-green-400" : isToday ? "bg-green-50" : ""
          }`}
        >
          <button
            onClick={() => go({ view: "day", date: cellDate })}
            className={`mb-1 inline-flex h-6 w-6 items-center justify-center rounded-full text-xs font-semibold transition-colors ${
              isToday ? "bg-green-500 text-white" : "text-gray-700 hover:bg-gray-100"
            }`}
          >
            {d}
          </button>
          <div className="space-y-0.5">
            {dayJobs.slice(0, 3).map((job) => (
              <div
                key={job.id}
                {...dragProps(job)}
                onClick={() => openItem(job)}
                className={`flex cursor-pointer items-center gap-1 truncate rounded-lg border-l-2 px-1.5 py-0.5 text-xs font-medium ${itemTone(job)}`}
                title={`${job.contactName} — ${job.title}`}
              >
                <TypeGlyph apptType={job.apptType} recurring={job.recurring} />
                <span className="truncate">
                  {job.scheduledAnytime ? "" : `${fmtTime(new Date(job.scheduledAt!))} `}
                  {job.contactName} — {job.title}
                </span>
              </div>
            ))}
            {dayJobs.length > 3 && (
              <button
                onClick={() => go({ view: "day", date: cellDate })}
                className="pl-1 text-xs text-gray-400 hover:text-gray-600 hover:underline"
              >
                +{dayJobs.length - 3} more
              </button>
            )}
          </div>
        </div>
      );
    }
    const total = firstDow + daysInMonth;
    if (total % 7 > 0) {
      for (let i = 0; i < 7 - (total % 7); i++) {
        cells.push(<div key={`t-${i}`} className="min-h-[80px] border-b border-r border-gray-100 bg-gray-50 p-1 lg:min-h-[104px]" />);
      }
    }

    return (
      <div className="overflow-hidden rounded-lg border border-gray-200 bg-white">
        <div className="grid grid-cols-7 border-b border-gray-100">
          {DAY_NAMES.map((d) => (
            <div key={d} className="py-2 text-center text-[11px] font-semibold uppercase tracking-wide text-gray-500">
              {d}
            </div>
          ))}
        </div>
        <div className="grid grid-cols-7">{cells}</div>
      </div>
    );
  }

  function renderTimeGrid() {
    const days = weekDays;
    const timed: Record<number, ScheduleJobDTO[]> = {};
    const anytime: Record<number, ScheduleJobDTO[]> = {};
    days.forEach((day, i) => {
      timed[i] = [];
      anytime[i] = [];
    });
    for (const job of jobs) {
      if (!job.scheduledAt) continue;
      const d = new Date(job.scheduledAt);
      const idx = days.findIndex((day) => sameDay(day, d));
      if (idx === -1) continue;
      (job.scheduledAnytime ? anytime : timed)[idx].push(job);
    }

    const gridCols = view === "week" ? "grid-cols-[56px_repeat(7,minmax(110px,1fr))]" : "grid-cols-[56px_minmax(0,1fr)]";
    const nowMin = today.getHours() * 60 + today.getMinutes();

    return (
      <div className="overflow-hidden rounded-lg border border-gray-200 bg-white">
        <div className={view === "week" ? "overflow-x-auto" : ""}>
          <div className={view === "week" ? "min-w-[840px]" : ""}>
            {/* Day headers */}
            <div className={`grid border-b border-gray-100 ${gridCols}`}>
              <div />
              {days.map((day, i) => {
                const isToday = sameDay(day, today);
                return (
                  <button
                    key={i}
                    onClick={() => view === "week" && go({ view: "day", date: day })}
                    className={`border-l border-gray-100 py-2 text-center ${view === "week" ? "hover:bg-gray-50" : "cursor-default"}`}
                  >
                    <span className="block text-[11px] font-semibold uppercase tracking-wide text-gray-500">
                      {DAY_NAMES[day.getDay()]}
                    </span>
                    <span
                      className={`mx-auto mt-0.5 flex h-7 w-7 items-center justify-center rounded-full text-sm font-semibold ${
                        isToday ? "bg-green-500 text-white" : "text-gray-900"
                      }`}
                    >
                      {day.getDate()}
                    </span>
                  </button>
                );
              })}
            </div>

            {/* Anytime row */}
            <div className={`grid border-b border-gray-200 ${gridCols}`}>
              <div className="flex items-start justify-end px-2 py-1.5">
                <span className="text-[11px] font-medium text-gray-400">Anytime</span>
              </div>
              {days.map((day, i) => {
                const key = `any-${i}`;
                return (
                  <div
                    key={i}
                    {...dropProps(key, day, "anytime")}
                    className={`min-h-[34px] space-y-0.5 border-l border-gray-100 p-1 transition-colors ${
                      hoverKey === key ? "bg-green-100/70 ring-2 ring-inset ring-green-400" : ""
                    }`}
                  >
                    {anytime[i].map((job) => (
                      <div
                        key={job.id}
                        {...dragProps(job)}
                        onClick={() => openItem(job)}
                        className={`cursor-pointer truncate rounded-lg border-l-2 px-1.5 py-0.5 text-xs font-medium ${itemTone(job)}`}
                        title={`${job.contactName} — ${job.title}`}
                      >
                        <TypeGlyph apptType={job.apptType} recurring={job.recurring} /> {job.contactName} — {job.title}
                      </div>
                    ))}
                  </div>
                );
              })}
            </div>

            {/* Hour grid */}
            <div ref={scrollRef} className="max-h-[60vh] overflow-y-auto lg:max-h-[calc(100vh-21rem)]">
              <div className={`grid ${gridCols}`}>
                {/* Time gutter */}
                <div>
                  {Array.from({ length: 24 }, (_, h) => (
                    <div key={h} className="relative border-b border-gray-50" style={{ height: HOUR_PX }}>
                      <span className="absolute -top-2 right-2 bg-white px-0.5 text-[10px] text-gray-400">
                        {h === 0 ? "" : hourLabel(h)}
                      </span>
                    </div>
                  ))}
                </div>
                {/* Day columns */}
                {days.map((day, i) => {
                  const isToday = sameDay(day, today);
                  const blocks = layoutTimed(timed[i], day);
                  return (
                    <div key={i} className={`relative border-l border-gray-100 ${isToday ? "bg-green-50/40" : ""}`}>
                      {Array.from({ length: 24 }, (_, h) => {
                        const key = `h-${i}-${h}`;
                        return (
                          <div
                            key={h}
                            {...dropProps(key, day, h)}
                            className={`border-b border-gray-50 transition-colors ${
                              hoverKey === key ? "bg-green-100/70 ring-2 ring-inset ring-green-400" : ""
                            }`}
                            style={{ height: HOUR_PX }}
                          />
                        );
                      })}
                      {/* current-time line (client-only to avoid hydration drift) */}
                      {mounted && isToday && (
                        <div
                          className="pointer-events-none absolute left-0 right-0 z-10 border-t-2 border-red-400"
                          style={{ top: (nowMin / 60) * HOUR_PX }}
                        >
                          <span className="absolute -left-1 -top-[5px] h-2 w-2 rounded-full bg-red-400" />
                        </div>
                      )}
                      {blocks.map(({ j, startMin, endMin, col, cols }) => (
                        <div
                          key={j.id}
                          {...dragProps(j)}
                          onClick={() => openItem(j)}
                          className={`absolute cursor-pointer overflow-hidden rounded-lg border-l-2 px-1.5 py-0.5 text-xs font-medium shadow-sm ${itemTone(j)}`}
                          style={{
                            top: (startMin / 60) * HOUR_PX + 1,
                            height: Math.max(22, ((endMin - startMin) / 60) * HOUR_PX - 2),
                            left: `calc(${(col / cols) * 100}% + 2px)`,
                            width: `calc(${(1 / cols) * 100}% - 4px)`,
                          }}
                          title={`${j.contactName} — ${j.title}`}
                        >
                          <span className="block truncate font-semibold">
                            <TypeGlyph apptType={j.apptType} recurring={j.recurring} /> {j.contactName}
                          </span>
                          <span className="block truncate">
                            {fmtTime(new Date(j.scheduledAt!))} · {j.title}
                          </span>
                        </div>
                      ))}
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // ── Mobile renderers ──────────────────────────────────────────────────────
  // Phones get a different calendar entirely. A 24-hour time grid asks you to
  // scroll a mostly-empty column to find two jobs, and month cells at 375px
  // truncate every chip to a few letters — so under lg the day/week views are
  // agendas and the month view is a dot grid, both tap-through to a day.

  const hue = SECTION_HUES.schedule;

  /** Items on a given day, Anytime first, then in clock order. */
  function itemsOn(day: Date): ScheduleJobDTO[] {
    return jobs
      .filter((j) => j.scheduledAt && sameDay(new Date(j.scheduledAt), day))
      .sort((a, b) => {
        if (a.scheduledAnytime !== b.scheduledAnytime) return a.scheduledAnytime ? -1 : 1;
        return new Date(a.scheduledAt!).getTime() - new Date(b.scheduledAt!).getTime();
      });
  }

  /** Week-at-a-glance date picker above the day agenda (iOS Calendar). */
  function renderDateStrip() {
    const days = Array.from({ length: 7 }, (_, i) => addDays(addDays(anchor, -anchor.getDay()), i));
    return (
      <div className="card-tool mb-3 flex overflow-hidden lg:hidden">
        {days.map((d, i) => {
          const selected = sameDay(d, anchor);
          const isToday = sameDay(d, today);
          const count = itemsOn(d).length;
          return (
            <button
              key={i}
              onClick={() => go({ view: "day", date: d })}
              aria-current={selected ? "date" : undefined}
              className="flex min-w-0 flex-1 flex-col items-center gap-1 py-2 transition-colors active:bg-gray-50"
            >
              <span className="text-[10px] font-semibold uppercase tracking-wide text-gray-400">
                {DAY_NAMES[d.getDay()][0]}
              </span>
              <span
                className="flex h-8 w-8 items-center justify-center rounded-full text-[15px] font-semibold"
                style={
                  // Brand accent, not the section hue — section color stays
                  // confined to the Create/More tiles (David's rule)
                  selected
                    ? {
                        backgroundColor: "var(--mobile-accent)",
                        color: "var(--mobile-on-accent)",
                      }
                    : isToday
                      ? {
                          backgroundColor:
                            "color-mix(in srgb, var(--mobile-accent) 14%, transparent)",
                          color: "var(--wb-ink)",
                        }
                      : undefined
                }
              >
                {d.getDate()}
              </span>
              {/* One dot per item, capped at three — "is there work here?" */}
              <span className="flex h-1.5 items-center gap-[3px]">
                {Array.from({ length: Math.min(count, 3) }, (_, k) => (
                  <span
                    key={k}
                    className="h-1.5 w-1.5 rounded-full"
                    style={{
                      backgroundColor: selected
                        ? "var(--mobile-accent)"
                        : "color-mix(in srgb, var(--mobile-accent) 55%, transparent)",
                    }}
                  />
                ))}
              </span>
            </button>
          );
        })}
      </div>
    );
  }

  /** "Marcus Reyes" → "MR" for the agenda's assignee chips. */
  function initialsOf(name: string): string {
    return name
      .split(/\s+/)
      .filter(Boolean)
      .map((w) => w[0]!)
      .slice(0, 2)
      .join("")
      .toUpperCase();
  }

  function agendaRow(it: ScheduleJobDTO) {
    const start = new Date(it.scheduledAt!);
    const end = it.scheduledEnd ? new Date(it.scheduledEnd) : null;
    const isBlock = it.kind === "block";
    const crew = !isBlock ? (it.assignees ?? []) : [];
    return (
      <li key={it.id}>
        <button
          type="button"
          onClick={() => openItem(it)}
          className="flex w-full items-stretch gap-2.5 text-left transition-transform active:scale-[0.99]"
        >
          {/* Time rail, like a printed day sheet */}
          <span className="w-[56px] shrink-0 pt-2 text-right">
            {it.scheduledAnytime ? (
              <span className="text-[11px] font-semibold text-gray-400">Anytime</span>
            ) : (
              <>
                <span className="numeral-ledger block text-[13px] font-semibold text-gray-900">
                  {fmtTime(start)}
                </span>
                {end && (
                  <span className="numeral-ledger block text-[11px] text-gray-400">
                    {fmtTime(end)}
                  </span>
                )}
              </>
            )}
          </span>
          <span
            className={`flex min-w-0 flex-1 items-center gap-2 rounded-[16px] border-l-[3px] px-3 py-2.5 shadow-[0_1px_2px_rgba(9,13,19,0.08)] ${itemTone(it)}`}
          >
            <span className="min-w-0 flex-1">
              <span className="flex items-center gap-1.5 text-[15px] font-semibold">
                <TypeGlyph apptType={it.apptType} recurring={it.recurring} size={13} />
                <span className="truncate">
                  {isBlock ? it.title || "Blocked off" : it.contactName}
                </span>
              </span>
              <span className="mt-0.5 block truncate text-[13px] opacity-80">
                {isBlock
                  ? it.contactName === "Everyone"
                    ? "Whole team"
                    : it.contactName
                  : it.title}
                {!isBlock && it.jobNumber ? ` · #${it.jobNumber}` : ""}
              </span>
              {it.tentative && (
                <span className="stamp mt-1.5 text-blue-800">Awaiting approval</span>
              )}
            </span>
            {/* Whose visit — reads at a glance on the Everyone view. The wash
                mixes from the row's own tone ink, so it works on every tint
                in both themes. */}
            {crew.length > 0 && (
              <span className="flex shrink-0 items-center gap-1 self-center">
                {crew.slice(0, 2).map((n, k) => (
                  <span
                    key={k}
                    className="flex h-6 w-6 items-center justify-center rounded-full text-[9.5px] font-bold"
                    style={{ background: "color-mix(in srgb, currentColor 14%, transparent)" }}
                    title={n}
                  >
                    {initialsOf(n)}
                  </span>
                ))}
                {crew.length > 2 && (
                  <span className="text-[10px] font-semibold opacity-70">+{crew.length - 2}</span>
                )}
              </span>
            )}
          </span>
        </button>
      </li>
    );
  }

  function renderAgenda(days: Date[]) {
    const nowMs = today.getTime();
    return (
      <div className="lg:hidden">
        {days.map((day, di) => {
          const items = itemsOn(day);
          const isToday = sameDay(day, today);
          // Where "now" falls in today's list — the red line native calendars draw
          const nowIdx =
            isToday && mounted
              ? items.findIndex(
                  (it) => !it.scheduledAnytime && new Date(it.scheduledAt!).getTime() > nowMs
                )
              : -1;
          // Single-day view opens with a human line, not a bare list — "what
          // does my day look like" answered before the first row.
          const firstTimed = items.find((it) => !it.scheduledAnytime);
          const summary =
            days.length === 1 && items.length > 0
              ? `${items.length} on the schedule${
                  firstTimed ? ` · first at ${fmtTime(new Date(firstTimed.scheduledAt!))}` : ""
                }`
              : null;
          return (
            <section key={di} className={di > 0 ? "mt-5" : ""}>
              {summary && (
                <p className="mb-2.5 px-0.5 text-[13px] font-medium text-gray-500">{summary}</p>
              )}
              {days.length > 1 && (
                <div className="mb-2 flex items-center gap-2 px-0.5">
                  <h3
                    className={`text-[13px] font-semibold ${
                      isToday ? "text-gray-900" : "text-gray-500"
                    }`}
                  >
                    {day.toLocaleDateString("en-US", {
                      weekday: "long",
                      month: "short",
                      day: "numeric",
                    })}
                  </h3>
                  {isToday && (
                    <span className="stamp" style={{ color: "var(--wb-ink)" }}>
                      Today
                    </span>
                  )}
                  <span className="h-px flex-1 bg-gray-200" aria-hidden />
                </div>
              )}
              {items.length === 0 ? (
                days.length > 1 ? (
                  // In a week, empty days stay a quiet line — seven "Nothing
                  // scheduled" cards buried the days that had work.
                  <p className="px-0.5 pb-1 text-[13px] text-gray-400">Nothing scheduled</p>
                ) : (
                  <div className="card-tool px-4 py-7 text-center">
                    <p className="text-sm font-medium text-gray-500">Nothing scheduled</p>
                    <p className="mt-0.5 text-xs text-gray-400">
                      {unscheduled.length > 0
                        ? `${unscheduled.length} job${unscheduled.length === 1 ? "" : "s"} waiting to be scheduled`
                        : "Free day."}
                    </p>
                  </div>
                )
              ) : (
                <ul className="space-y-2">
                  {items.flatMap((it, i) =>
                    i === nowIdx
                      ? [
                          <li
                            key={`now-${di}`}
                            aria-hidden
                            className="flex items-center gap-2 py-1"
                          >
                            {/* Now — the concept's orange line, stamped with
                                the actual time in the rail (mounted-only, so
                                no hydration drift) */}
                            <span
                              className="numeral-ledger w-[56px] shrink-0 text-right text-[11px] font-bold"
                              style={{ color: "#F86A0A" }}
                            >
                              {fmtTime(new Date())}
                            </span>
                            <span
                              className="h-2 w-2 shrink-0 rounded-full"
                              style={{ backgroundColor: "#F86A0A" }}
                            />
                            <span
                              className="h-[2px] flex-1 rounded-full"
                              style={{ backgroundColor: "#F86A0A" }}
                            />
                          </li>,
                          agendaRow(it),
                        ]
                      : [agendaRow(it)]
                  )}
                </ul>
              )}
            </section>
          );
        })}
      </div>
    );
  }

  /** Month grid + the selected day's agenda inline beneath it (the native
      calendar-app pattern) — tapping a day answers "what's happening that
      day" right there instead of yanking you into the day view. */
  function renderMonthCompact() {
    const y = anchor.getFullYear();
    const m = anchor.getMonth();
    const firstDow = new Date(y, m, 1).getDay();
    const daysInMonth = new Date(y, m + 1, 0).getDate();

    const byDay: Record<number, ScheduleJobDTO[]> = {};
    for (const job of jobs) {
      if (!job.scheduledAt) continue;
      const d = new Date(job.scheduledAt);
      if (d.getMonth() !== m || d.getFullYear() !== y) continue;
      (byDay[d.getDate()] ??= []).push(job);
    }

    return (
      <div className="lg:hidden">
        <div className="card-tool overflow-hidden">
          <div className="grid grid-cols-7 border-b border-gray-100 py-1.5">
            {DAY_NAMES.map((d) => (
              <div key={d} className="text-center text-[10px] font-semibold uppercase text-gray-400">
                {d[0]}
              </div>
            ))}
          </div>
          <div className="grid grid-cols-7 gap-y-0.5 px-1 py-2">
            {Array.from({ length: firstDow }, (_, i) => (
              <div key={`e-${i}`} />
            ))}
            {Array.from({ length: daysInMonth }, (_, i) => {
              const d = i + 1;
              const cellDate = new Date(y, m, d);
              const isToday = sameDay(cellDate, today);
              const selected = sameDay(cellDate, anchor);
              const dayItems = byDay[d] ?? [];
              return (
                <button
                  key={d}
                  onClick={() => go({ date: cellDate })}
                  aria-current={selected ? "date" : undefined}
                  className="flex flex-col items-center gap-1 rounded-xl py-1.5 transition-colors active:bg-gray-50"
                >
                  {/* Plain days take their ink from the class, never an inline
                      color: inline styles outrank the dark-theme bridge in
                      globals.css, so a hardcoded gray-900 stayed near-black on
                      the dark card and every day but today read as blank.
                      Selected = solid accent, today (unselected) = accent wash
                      — same grammar as the day-view date strip. */}
                  <span
                    className={`flex h-8 w-8 items-center justify-center rounded-full text-[15px] font-medium ${
                      selected || isToday ? "" : "text-gray-900"
                    }`}
                    style={
                      selected
                        ? {
                            backgroundColor: "var(--mobile-accent)",
                            color: "var(--mobile-on-accent)",
                          }
                        : isToday
                          ? {
                              backgroundColor:
                                "color-mix(in srgb, var(--mobile-accent) 14%, transparent)",
                              color: "var(--wb-ink)",
                            }
                          : undefined
                    }
                  >
                    {d}
                  </span>
                  {/* One dot per item (capped) in a single accent tint: the
                      lifecycle tones a legend would decode collapse into
                      near-identical blues once a tenant's accent replaces the
                      stock green, so the dots only claim "there's work here" —
                      the agenda below carries the detail. */}
                  <span className="flex h-1.5 items-center gap-[3px]">
                    {dayItems.slice(0, 3).map((it) => (
                      <span
                        key={it.id}
                        className="h-1.5 w-1.5 rounded-full"
                        style={{
                          backgroundColor: selected
                            ? "var(--mobile-accent)"
                            : "color-mix(in srgb, var(--mobile-accent) 55%, transparent)",
                        }}
                      />
                    ))}
                  </span>
                </button>
              );
            })}
          </div>
        </div>

        {/* The selected day, right below the grid */}
        <div className="mb-2 mt-4 flex items-center gap-2 px-0.5">
          <h3 className="text-[13px] font-semibold text-gray-900">
            {anchor.toLocaleDateString("en-US", {
              weekday: "long",
              month: "short",
              day: "numeric",
            })}
          </h3>
          {sameDay(anchor, today) && (
            <span className="stamp" style={{ color: "var(--wb-ink)" }}>
              Today
            </span>
          )}
          <span className="h-px flex-1 bg-gray-200" aria-hidden />
          <button
            onClick={() => go({ view: "day" })}
            className="text-[13px] font-semibold text-green-700"
          >
            Day view
          </button>
        </div>
        {renderAgenda([anchor])}
      </div>
    );
  }

  // ── Page ──────────────────────────────────────────────────────────────────
  return (
    <div className="mx-auto max-w-7xl p-4 lg:p-8">
      {/* Header — actions are icon circles on phones (labels return at md)
          so the row breathes instead of cramming three long buttons. */}
      <div className="mb-5 flex items-center justify-between gap-2">
        <PageTitle section="schedule" icon={CalendarDays}>
          Schedule
        </PageTitle>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setDrawerOpen((o) => !o)}
            aria-label="Unscheduled jobs"
            title="Unscheduled"
            className={`relative flex h-10 w-10 items-center justify-center gap-1.5 rounded-[10px] text-sm font-semibold transition-colors md:w-auto md:px-4 ${
              drawerOpen
                ? "chip-pressed bg-green-50 text-green-700"
                : "btn-tool-line bg-white text-gray-700 hover:bg-gray-50"
            }`}
          >
            <CalendarDays size={16} />
            <span className="hidden md:inline">Unscheduled</span>
            {unscheduled.length > 0 && (
              <span className="absolute -right-1 -top-1 min-w-[18px] rounded-full bg-amber-400 px-1 py-px text-center text-[11px] font-bold text-amber-950 md:static md:bg-amber-100 md:text-amber-700">
                {unscheduled.length}
              </span>
            )}
          </button>
          <button
            onClick={openBlockCreate}
            aria-label="Block off time"
            title="Block Time"
            className="flex h-10 w-10 items-center justify-center gap-1.5 rounded-[10px] btn-tool-line bg-white text-sm font-semibold text-gray-700 transition-colors hover:bg-gray-50 md:w-auto md:px-4"
          >
            <CalendarOff size={16} />
            <span className="hidden md:inline">Block Time</span>
          </button>
          {/* Phones create appointments from the tab-bar FAB's Create sheet */}
          {canCreateAppointment && (
            <Link
              href="/app/appointments/new"
              aria-label="New appointment"
              title="New Appointment"
              className="hidden h-10 items-center justify-center gap-1.5 rounded-[10px] btn-tool-line bg-blue-50 px-4 text-sm font-semibold text-blue-700 transition-colors hover:bg-blue-100 md:flex"
            >
              <CalendarClock size={16} />
              New Appointment
            </Link>
          )}
          {/* Phones create from the tab-bar FAB */}
          {canCreateJob && (
            <Link
              href="/app/jobs/new"
              className="hidden lg:flex h-10 items-center gap-1.5 rounded-[10px] btn-tool bg-green-500 px-4 text-sm font-semibold text-white transition-colors hover:bg-green-600 active:bg-green-700"
            >
              <Plus size={15} />
              New Job
            </Link>
          )}
        </div>
      </div>

      {/* ── Mobile controls: a centered date title flanked by chevrons (the
             native calendar header), then one scrolling chip rail. The old
             wrapping flex row stacked three lines of chrome above the
             calendar and pushed the day itself below the fold. ── */}
      <div className="mb-2.5 flex items-center gap-1 lg:hidden">
        <button
          onClick={() => step(-1)}
          className="-ml-1.5 shrink-0 rounded-full p-2 transition-colors active:bg-gray-100"
          aria-label="Previous"
        >
          <ChevronLeft size={20} className="text-gray-500" />
        </button>
        <h2 className="min-w-0 flex-1 truncate text-center text-[17px] font-bold text-gray-900">
          {shortLabel}
        </h2>
        <button
          onClick={() => step(1)}
          className="shrink-0 rounded-full p-2 transition-colors active:bg-gray-100"
          aria-label="Next"
        >
          <ChevronRight size={20} className="text-gray-500" />
        </button>
        {/* Redundant while the title already says "Today" */}
        {!sameDay(anchor, today) && (
          <button
            onClick={() => go({ date: new Date() })}
            className="shrink-0 rounded-[10px] btn-tool-line bg-white px-2.5 py-1.5 text-[13px] font-semibold text-gray-700"
          >
            Today
          </button>
        )}
      </div>
      {/* One fixed row — segmented view control + team picker, everything
          visible without sideways scrolling */}
      <div className="mb-4 flex items-center gap-2 lg:hidden">
        <SegmentedRow className="min-w-0 flex-1">
          {(["day", "week", "month"] as View[]).map((v) => (
            <Segment key={v} active={view === v} onClick={() => go({ view: v })}>
              <span className="capitalize">{v}</span>
            </Segment>
          ))}
        </SegmentedRow>
        {users.length > 1 && (
          <select
            value={team}
            onChange={(e) => go({ team: e.target.value })}
            aria-label="Team member"
            className="max-w-[128px] shrink-0 rounded-[10px] border border-gray-200 bg-white py-2 pl-3 pr-2 text-[13px] font-medium text-gray-700 focus:outline-none focus:ring-2 focus:ring-green-500"
          >
            <option value="">Everyone</option>
            {users.map((u) => (
              <option key={u.id} value={u.id}>
                {u.name}
              </option>
            ))}
          </select>
        )}
        {(saving || isPending) && (
          <Loader2 size={15} className="shrink-0 animate-spin text-gray-400" />
        )}
      </div>

      {/* ── Desktop controls ── */}
      <div className="mb-4 hidden flex-wrap items-center gap-x-2 gap-y-2 lg:flex">
        <div className="flex items-center gap-1">
          <button onClick={() => step(-1)} className="rounded-full p-2 transition-colors hover:bg-gray-100" aria-label="Previous">
            <ChevronLeft size={18} className="text-gray-600" />
          </button>
          <button onClick={() => step(1)} className="rounded-full p-2 transition-colors hover:bg-gray-100" aria-label="Next">
            <ChevronRight size={18} className="text-gray-600" />
          </button>
          <button
            onClick={() => go({ date: new Date() })}
            className="rounded-[10px] btn-tool-line bg-white px-3 py-1.5 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50"
          >
            Today
          </button>
        </div>

        <h2 className="text-base font-bold text-gray-900 lg:text-lg">{rangeLabel}</h2>
        {(saving || isPending) && <Loader2 size={15} className="animate-spin text-gray-400" />}

        <div className="ml-auto flex items-center gap-2">
          <div className="flex shrink-0 items-center gap-1.5">
            {(["month", "week", "day"] as View[]).map((v) => (
              <FilterChip key={v} hue={hue} active={view === v} onClick={() => go({ view: v })}>
                <span className="capitalize">{v}</span>
              </FilterChip>
            ))}
          </div>
          {users.length > 1 && (
            <select
              value={team}
              onChange={(e) => go({ team: e.target.value })}
              className="min-w-0 rounded-[10px] border border-gray-300 bg-white px-3 py-1.5 text-sm text-gray-700 focus:outline-none focus:ring-2 focus:ring-green-500"
            >
              <option value="">All team members</option>
              {users.map((u) => (
                <option key={u.id} value={u.id}>
                  {u.name}
                </option>
              ))}
            </select>
          )}
        </div>
      </div>

      {error && (
        <div className="mb-3 flex items-center justify-between rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
          {error}
          <button onClick={() => setError("")} className="p-0.5 text-red-400 hover:text-red-600">
            <X size={14} />
          </button>
        </div>
      )}

      {/* Calendar + drawer */}
      <div className="flex items-start gap-4">
        <div className={`min-w-0 flex-1 ${isPending ? "opacity-60" : ""}`}>
          {/* Phones: date strip + agenda, or the month dot grid */}
          {view === "month" ? (
            renderMonthCompact()
          ) : (
            <>
              {view === "day" && renderDateStrip()}
              {renderAgenda(weekDays)}
            </>
          )}

          {/* Desktop: the full month grid / hour grid */}
          <div className="hidden lg:block">
            {view === "month" ? renderMonth() : renderTimeGrid()}
          </div>

          {/* Legend — desktop only: the agenda's rows name themselves, and the
              month dots are deliberately single-colored. */}
          <div className="mt-4 hidden flex-wrap gap-3 lg:flex">
            {[
              ["bg-green-500", "Active job"],
              ["bg-amber-500", "Requires invoicing"],
              ["bg-blue-500", "Appointment"],
              ["bg-gray-400", "Closed"],
              ["bg-blocked border border-gray-400", "Blocked off"],
            ].map(([c, label]) => (
              <div key={label} className="flex items-center gap-1.5 text-xs text-gray-500">
                <div className={`h-2.5 w-2.5 rounded-lg ${c}`} />
                {label}
              </div>
            ))}
          </div>
        </div>

        {/* Unscheduled drawer */}
        {drawerOpen && (
          <aside className="sheet-rise sticky top-4 w-72 shrink-0 rounded-lg border border-gray-200 bg-white max-lg:fixed max-lg:inset-x-0 max-lg:bottom-0 max-lg:top-auto max-lg:z-40 max-lg:max-h-[70dvh] max-lg:w-full max-lg:overflow-y-auto max-lg:overscroll-y-contain max-lg:rounded-t-2xl max-lg:rounded-b-none max-lg:border-x-0 max-lg:border-b-0 max-lg:pb-[env(safe-area-inset-bottom)] max-lg:shadow-[0_-8px_30px_rgba(28,25,23,0.18)]">
            <div className="mx-auto mt-2 h-1 w-9 rounded-full bg-gray-200 lg:hidden" />
            <div className="flex items-center justify-between border-b border-gray-100 px-4 py-3">
              <h3 className="text-sm font-semibold text-gray-900">
                Unscheduled jobs{unscheduled.length > 0 && ` (${unscheduled.length})`}
              </h3>
              <button onClick={() => setDrawerOpen(false)} className="p-1 text-gray-400 hover:text-gray-600">
                <X size={15} />
              </button>
            </div>
            {unscheduled.length === 0 ? (
              <p className="px-4 py-8 text-center text-sm text-gray-500">
                Nothing waiting to be scheduled. New jobs without a date will show up here.
              </p>
            ) : (
              <>
                <p className="px-4 pt-3 text-xs text-gray-400 max-lg:hidden">
                  Drag a job onto the calendar to schedule it.
                </p>
                {/* Touch has no drag-and-drop — on phones the row opens the
                    job, where the date lives. */}
                <p className="px-4 pt-2.5 text-xs text-gray-400 lg:hidden">
                  Tap a job to open it and give it a date.
                </p>
                <ul className="space-y-2 p-3">
                  {unscheduled.map((job) => (
                    <li
                      key={job.id}
                      {...dragProps(job)}
                      onClick={() => openItem(job)}
                      className={`flex cursor-pointer items-center gap-2.5 rounded-[12px] border border-gray-200 bg-white p-3 transition-colors hover:border-green-300 hover:bg-green-50/50 active:bg-gray-50 lg:p-2.5 ${
                        dragId === job.id ? "opacity-50" : ""
                      }`}
                    >
                      <GripVertical size={14} className="shrink-0 text-gray-300 max-lg:hidden" />
                      <div className="min-w-0 flex-1">
                        <p className="truncate text-[15px] font-medium text-gray-900 lg:text-sm">
                          {job.title}
                        </p>
                        <p className="truncate text-xs text-gray-500">
                          {job.contactName} · Job #{job.jobNumber}
                        </p>
                      </div>
                      <ChevronRight size={16} className="shrink-0 text-gray-300 lg:hidden" />
                    </li>
                  ))}
                </ul>
              </>
            )}
          </aside>
        )}
        {drawerOpen && (
          <div className="fixed inset-0 z-30 bg-black/20 lg:hidden" onClick={() => setDrawerOpen(false)} />
        )}
      </div>

      {/* Block-off-time sheet (create + edit; read-only when not yours) */}
      {blockSheet && (
        <div
          className="modal-pop fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4"
          onClick={() => !blockBusy && setBlockSheet(null)}
        >
          <div
            className="modal-card w-full max-w-md space-y-3 rounded-lg bg-white p-5 text-left shadow-xl"
            onClick={(e) => e.stopPropagation()}
          >
            <h2 className="text-base font-semibold text-gray-900">
              {blockSheet.id === null
                ? "Block Off Time"
                : blockSheet.canEdit
                  ? "Edit Blocked Time"
                  : "Blocked Time"}
            </h2>

            {!blockSheet.canEdit && (
              <p className="text-sm text-gray-500">
                {blockSheet.form.who === "everyone"
                  ? "Blocked off for the whole team by an owner or admin."
                  : "Only owners and admins can change someone else's blocked time."}
              </p>
            )}

            {blockErr && (
              <div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
                {blockErr}
              </div>
            )}

            <div>
              <label className="mb-0.5 block text-xs font-medium text-gray-500">Reason</label>
              <input
                type="text"
                value={blockSheet.form.title}
                disabled={!blockSheet.canEdit}
                placeholder="Blocked off"
                onChange={(e) =>
                  setBlockSheet((s) => s && { ...s, form: { ...s.form, title: e.target.value } })
                }
                className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-green-500 disabled:bg-gray-50 disabled:text-gray-500"
              />
            </div>

            {canBlockForOthers ? (
              <div>
                <label className="mb-0.5 block text-xs font-medium text-gray-500">Who</label>
                <select
                  value={blockSheet.form.who}
                  onChange={(e) =>
                    setBlockSheet((s) => s && { ...s, form: { ...s.form, who: e.target.value } })
                  }
                  className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-green-500"
                >
                  <option value="everyone">Everyone (whole team)</option>
                  {users.map((u) => (
                    <option key={u.id} value={u.id}>
                      {u.id === meId ? `${u.name} (me)` : u.name}
                    </option>
                  ))}
                </select>
              </div>
            ) : (
              blockSheet.id !== null &&
              !blockSheet.canEdit && (
                <p className="text-xs text-gray-500">
                  Applies to:{" "}
                  {blockSheet.form.who === "everyone" ? "everyone" : blockSheet.userName ?? "a teammate"}
                </p>
              )
            )}

            <label className="flex items-center gap-2 text-sm text-gray-700">
              <input
                type="checkbox"
                checked={blockSheet.form.allDay}
                disabled={!blockSheet.canEdit}
                onChange={(e) =>
                  setBlockSheet((s) => s && { ...s, form: { ...s.form, allDay: e.target.checked } })
                }
                className="rounded text-green-600 focus:ring-green-500"
              />
              All day
            </label>

            {blockSheet.form.allDay ? (
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="mb-0.5 block text-xs font-medium text-gray-500">From</label>
                  <input
                    type="date"
                    value={blockSheet.form.startDate}
                    disabled={!blockSheet.canEdit}
                    onChange={(e) =>
                      setBlockSheet((s) => {
                        if (!s) return s;
                        const startDate = e.target.value;
                        const endDate = s.form.endDate < startDate ? startDate : s.form.endDate;
                        return { ...s, form: { ...s.form, startDate, endDate } };
                      })
                    }
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-green-500 disabled:bg-gray-50 disabled:text-gray-500"
                  />
                </div>
                <div>
                  <label className="mb-0.5 block text-xs font-medium text-gray-500">Through</label>
                  <input
                    type="date"
                    value={blockSheet.form.endDate}
                    disabled={!blockSheet.canEdit}
                    onChange={(e) =>
                      setBlockSheet((s) => s && { ...s, form: { ...s.form, endDate: e.target.value } })
                    }
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-green-500 disabled:bg-gray-50 disabled:text-gray-500"
                  />
                </div>
              </div>
            ) : (
              <>
                <div>
                  <label className="mb-0.5 block text-xs font-medium text-gray-500">Date</label>
                  <input
                    type="date"
                    value={blockSheet.form.startDate}
                    disabled={!blockSheet.canEdit}
                    onChange={(e) =>
                      setBlockSheet((s) => s && { ...s, form: { ...s.form, startDate: e.target.value } })
                    }
                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-green-500 disabled:bg-gray-50 disabled:text-gray-500"
                  />
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="mb-0.5 block text-xs font-medium text-gray-500">From</label>
                    <input
                      type="time"
                      value={blockSheet.form.startTime}
                      disabled={!blockSheet.canEdit}
                      onChange={(e) =>
                        setBlockSheet((s) => s && { ...s, form: { ...s.form, startTime: e.target.value } })
                      }
                      className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-green-500 disabled:bg-gray-50 disabled:text-gray-500"
                    />
                  </div>
                  <div>
                    <label className="mb-0.5 block text-xs font-medium text-gray-500">To</label>
                    <input
                      type="time"
                      value={blockSheet.form.endTime}
                      disabled={!blockSheet.canEdit}
                      onChange={(e) =>
                        setBlockSheet((s) => s && { ...s, form: { ...s.form, endTime: e.target.value } })
                      }
                      className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-green-500 disabled:bg-gray-50 disabled:text-gray-500"
                    />
                  </div>
                </div>
              </>
            )}

            <div className="flex items-center gap-2 pt-1">
              {blockSheet.canEdit && (
                <button
                  onClick={saveBlock}
                  disabled={blockBusy}
                  className="flex items-center gap-2 rounded-[10px] btn-tool bg-green-500 px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-green-600 active:bg-green-700 disabled:opacity-50"
                >
                  {blockBusy && <Loader2 size={14} className="animate-spin" />}
                  {blockSheet.id === null ? "Block Time" : "Save"}
                </button>
              )}
              <button
                onClick={() => setBlockSheet(null)}
                disabled={blockBusy}
                className="rounded-[10px] btn-tool-line bg-white px-4 py-2 text-sm font-medium text-gray-600 transition-colors hover:bg-gray-50"
              >
                {blockSheet.canEdit ? "Cancel" : "Close"}
              </button>
              {blockSheet.canEdit && blockSheet.id !== null && (
                <button
                  onClick={deleteBlock}
                  disabled={blockBusy}
                  aria-label="Remove blocked time"
                  className="ml-auto flex items-center gap-1.5 rounded-[10px] px-3 py-2 text-sm font-medium text-red-600 transition-colors hover:bg-red-50"
                >
                  <Trash2 size={14} />
                  Remove
                </button>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
